# Macro file to run the simulation 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
#
#
# Initialize kernel
/process/optical/scintillation/setFiniteRiseTime 1
/run/initialize
#
/control/verbose 0 #2
/run/verbose 0 #2
/event/verbose 0 #0
/tracking/verbose 0 #1
/run/particle/verbose 0
/process/verbose 0
#
#
#/gun/particle monopole
#/gun/calibenergy 1
#/gun/xvertex -500
# 
#
#
/run/beamOn 500
